### ISSUE TITLE
Thread adoption

### ISSUE THREAD

**Issue by Taaitaaiger** [Clemapfel/jluna#45] opened 2023-02-19 18:36 UTC
Hi!

I've got to admit I'm not a user of JLuna, but rather someone who's working on a similar library. Considering you've put a lot of effort in mutithreading support, I think you might also be interested in thread adoption. This is a feature that will be available in Julia 1.9 that can be used to create a pool of threads that can call into Julia.

Feel free to ask any questions you have, or close this issue if you're not interested :)

**Comment by Clemapfel** [comment] 2023-02-20 02:11
Thank you, I was aware of this feature the moment the PR for it was opened on the Julia GitHub, just a few days ago (https://github.com/Clemapfel/jluna/issues/42) I was informed how the crash is related to thread local storage, which is interesting. I might update the docs with that context.

I'll be deprecating the jluna multi-threading modules once 1.9 becomes stable, however, that will be many months in the future, I'm sure.
 
Thank you for thinking of informing me, I feel like it's possible to feel the undercurrent of frustration in how I wrote the multi-threading docs, mostly because I spend 3 days trying to reverse engineer the crash thinking it was a bug. I'm actually still kinda upset about that but what's done is done.

I'll be closing this issue as a duplicate of https://github.com/Clemapfel/jluna/issues/26 and https://github.com/Clemapfel/jluna/issues/42

**Closed by Clemapfel** 2023-02-20 02:11 UTC
Labels: duplicate, critique, acknowledged

**Comment by Taaitaaiger** [comment] 2023-02-20 20:23
Ah, I see I should have checked the closed issues before I opened this,
sorry for the noise.

The first RC for 1.9 seems to be around the corner, given that a pr was
opened for it, so let's hope it's a few weeks rather than several months 😉

Op ma 20 feb. 2023 03:11 schreef Clem Cords ***@***.***>:
