### ISSUE TITLE
Installation Issue with MinGW_64

### ISSUE THREAD

**Issue by riatankarsahu** [Clemapfel/jluna#41] opened 2023-02-15 18:55 UTC
Hi,
I was trying to install that library as I saw it supposed to be quite handy. But after several tries, I couldn't do it. After getting successful build I don't have the dll file in release or debug folder.

Build Command I used 

1.  cmake .. -DCMAKE_CXX_COMPILER=<clang++> -DCMAKE_INSTALL_PREFIX=<E:\Jluna> -G "Ninja Multi-Config" (The CXX compiler identification is Clang 15.0.7)
2.  cmake .. -DCMAKE_CXX_COMPILER=<g++> -DCMAKE_INSTALL_PREFIX=<E:\Jluna> -G "Ninja Multi-Config"

I don't really get what's the actual problem I am sending the console and the build directory screenshot for further evaluation. If you help me, I will be grateful to you! Thank you in advance.

![image](https://user-images.githubusercontent.com/40383487/219125301-067ffe55-c1ce-41e4-b04a-845aadf10699.png)

![image](https://user-images.githubusercontent.com/40383487/219125374-04c7df31-e60e-409c-ac9a-6f302204f3eb.png)

**Comment by Clemapfel** [comment] 2023-02-16 21:21
I think your command contains `-DCMAKE_INSTALL_PREFIX=<E:/Jluna>` with a capital `J` but your folder is name `jluna` (with a lowercase j)

**Comment by riatankarsahu** [comment] 2023-02-16 23:04
Hi,
I tried, but didn't work. I am showing you the installpath, command and build directory screenshot. again.
I think something is strictly mentioned in CMakeLists.txt file which is blocking the generation. If you allow me I can analyze the code, and if I find something, I will let you know. Meanwhile please have a look at the present status.

InstallPath:
![image](https://user-images.githubusercontent.com/40383487/219507624-6f26bdd1-51e2-43f5-8db7-7eb062ef9844.png)

Build Directory:
![image](https://user-images.githubusercontent.com/40383487/219507766-e277f066-1655-4564-8312-354a8c2fc5b9.png)

Console:
![image](https://user-images.githubusercontent.com/40383487/219507920-8fb14f4a-98c4-4ee7-8145-9806e563fb82.png)

**Comment by Clemapfel** [comment] 2023-02-17 16:11
Have you executed `make`?

**Comment by riatankarsahu** [comment] 2023-02-17 16:56
Yeah I have executed the build. Not with 'make' rather with 'ninja'. Sending the output to you, please have a glance at the text file. :) 
[Output.txt](https://github.com/Clemapfel/jluna/files/10769043/Output.txt)

**Comment by Clemapfel** [comment] 2023-02-17 17:51
None of these errors are triggered by jluna code, they are by your C++ standard library implementation.

I will attempt to reproduce this on a virtual machine (I don't have access to a windows workstation) and get back to you

**Comment by riatankarsahu** [comment] 2023-02-17 18:05
Ok meanwhile I will also try to change the C++ version and try once again. Thank you so much! And also I have to mention this work in my thesis. So if you allow me to know about the research work you are doing on jluna, it would be great pleasure!

**Comment by Clemapfel** [comment] 2023-02-17 18:22
Either way the fix for this will be a big windows-support PR which will take time. 

If you'd like to fork jluna and try to make it work I'd be happy to credit you as a co-author with getting Windows running. I assume it is related to how the C++ standard library is linked or included so I would expect the fix to either modify jlunas [CMakeLists.txt](https://github.com/Clemapfel/jluna/blob/master/CMakeLists.txt) or [this header](https://github.com/Clemapfel/jluna/blob/master/include/julia_wrapper.hpp).

I don't have any development experience on Windows so (on top of not owning a physical Windows PC) I'm not very good at troubleshooting Windows issues but I feel like it was only a matter of time until this had to be done. If Julia is portable, jluna should be too

**Comment by riatankarsahu** [comment] 2023-02-17 18:35
Honestly I would be happy to help with this issue. Thank you so much for your offer! I will start working on that since tomorrow. And will keep you updated.

**Comment by riatankarsahu** [comment] 2023-02-18 17:13
Hello,

The problem is resolved. Your work is perfect! (Y)

![image](https://user-images.githubusercontent.com/40383487/219878640-5084dc83-51a6-4e72-8316-b4d5e932d83d.png)

An update I wish to add here, which is my research analysis so far. Yet we can't use clang/clang++/clang-cl/clang-cl++ as builder in windows to build that repository. The fact is 'libc++' isn't yet ready to be compatible with cxx_std_20 for windows. So the build will be failed. 'libstdc++' & 'libgcc' are fully compatible with cxx_std_20 but in that case we always need to select 'g++' as builder. Also I will recommend 'Ninja' as build tool for it's speed. If you wish to inform all the users about this feature, please mention this part in 'README.md'

So for that small amount of work I don't need the co-author title. But I need your details to put in my thesis, as I will use 'jluna' in my project as Julia -> C/C++ binder. 

Once again thank you so much for your time and help!! Have a great weekend ahead!!

**Comment by Clemapfel** [comment] 2023-02-19 15:32
> Also I will recommend 'ninja' as build tool for it's speed
Users are free to use whatever build tool or linker they want, `make` comes with cmake so inexperienced users have one less thing to install, which is why I chose to not mention something like ninja, even though I personally also prefer to use it

> I need your details to put in my thesis, as I will use 'jluna' in my project as Julia -> C/C++ binder
You can find details for the citation [here](https://github.com/Clemapfel/jluna#license)

> The fact is 'libc++' isn't yet ready to be compatible with cxx_std_20 for windows. 
I will keep this issue open and investigate this, clang should work since gcc is hardly native to windows. Once I have the windows environment set up, I'll also try to get MSVC working

**Comment by Clemapfel** [comment] 2023-02-22 18:34
Fixed by #46, closing

**Closed by Clemapfel** 2023-02-22 18:34 UTC
Labels: compiler error, acknowledged, windows
